export const ErrorType = {
  CUSTOMER_NOT_FOUND: "CUSTOMER_NOT_FOUND",
  INVALID_EMAIL_FORMAT: "INVALID_EMAIL_FORMAT",
  JOB_NOT_FOUND: "JOB_NOT_FOUND",
  JOB_CUSTOMER_NOT_EXIST: "JOB_CUSTOMER_NOT_EXIST",
  APPOINTMENT_OVERLAP: "APPOINTMENT_OVERLAP",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  JOB_NO_APPOINTMENT: "JOB_NO_APPOINTMENT",
  JOB_NOT_DONE: "JOB_NOT_DONE",
  INVALID_STATUS_UPDATE: "INVALID_STATUS_UPDATE",
  INVALID_TRANSITION: "INVALID_TRANSITION",

  CUSTOMER_NAME_REQUIRED: "CUSTOMER_NAME_REQUIRED",
  CUSTOMER_EMAIL_REQUIRED: "CUSTOMER_EMAIL_REQUIRED",
  INVALID_PHONE_FORMAT: "INVALID_PHONE_FORMAT",
  CUSTOMER_EMAIL_EXISTS: "CUSTOMER_EMAIL_EXISTS",
  DUPLICATE_ENTRY: "DUPLICATE_ENTRY",

  INVALID_PAYMENT: "INVALID_PAYMENT",
} as const;

export type ErrorTypeType = (typeof ErrorType)[keyof typeof ErrorType];
