export const ErrorCode = {
  ACCESS_UNAUTHORIZED: "ACCESS_UNAUTHORIZED",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  CUSTOMER_NOT_FOUND: "CUSTOMER_NOT_FOUND",
  INVALID_EMAIL_FORMAT: "INVALID_EMAIL_FORMAT",
  JOB_CUSTOMER_NOT_EXIST: "JOB_CUSTOMER_NOT_EXIST",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
