export const ErrorCode = {
  CUSTOMER_NOT_FOUND: "CUSTOMER_NOT_FOUND",
  INVALID_EMAIL_FORMAT: "INVALID_EMAIL_FORMAT",
  JOB_NOT_FOUND: "JOB_NOT_FOUND",
  JOB_CUSTOMER_NOT_EXIST: "JOB_CUSTOMER_NOT_EXIST",
  APPOINTMENT_OVERLAP: "APPOINTMENT_OVERLAP",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCodeType = typeof ErrorCode[keyof typeof ErrorCode];
